# Environment file for the LUNA Run Control
name: luna

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - numpy
  - matplotlib
  - jupyter
  - ipykernel
  - ipywidgets
  - jupyterlab
  - flask
  - flask-sqlalchemy
  - flask-migrate
  - flask-jwt-extended
  - flask-cors
  - root=6.30.4
  - pycurl
  - pkgconfig
  - pip
  - pip:
    - docker
    - waitress