"""add charge

Revision ID: 04da16c14b89
Revises: 58bdc61d08b1
Create Date: 2024-10-30 18:18:02.020643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04da16c14b89'
down_revision = '58bdc61d08b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accumulated_charge', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_metadata', schema=None) as batch_op:
        batch_op.drop_column('accumulated_charge')

    # ### end Alembic commands ###
