"""Initial migration.

Revision ID: 8678444db75c
Revises: 
Create Date: 2026-04-26 14:12:42.142887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8678444db75c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('run_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('accumulated_charge', sa.Float(), nullable=True),
    sa.Column('target_name', sa.String(length=64), nullable=True),
    sa.Column('terminal_voltage', sa.Float(), nullable=True),
    sa.Column('probe_voltage', sa.Float(), nullable=True),
    sa.Column('run_type', sa.String(length=64), nullable=True),
    sa.Column('flag', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_metadata_run_number'), ['run_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_metadata_run_number'))

    op.drop_table('run_metadata')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
